import './styles/globals.css';
import Link from 'next/link';
import { ReactNode } from 'react';
import Image from 'next/image';

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<head>
				<title>Layouts</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className="flex w-screen h-screen">
				<aside className="flex flex-col mr-8 p-4">
					<div className="relative w-20 h-20 overflow-hidden rounded-full">
						<Image
							src="https://media.istockphoto.com/vectors/compass-icon-on-white-background-vector-id1051381666?k=20&m=1051381666&s=612x612&w=0&h=mWRX37HFxb6rOc7V-U_2U1g1m_-2dxG7pOKchGAo8Rs="
							alt="compass"
							fill
						/>
					</div>
					<Link href={`/UK/information`}>UK</Link>
					<Link href={`/USA/information`}>USA</Link>
					<Link href={`/Australia/information`}>Australia</Link>
				</aside>
				<section>{children}</section>
			</body>
		</html>
	);
}
