export default function Head({ params }: { params: { name: string } }) {
	return (
		<head>
			<title>{params.name}</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="stylesheet" href="../styles/globals.css" />
		</head>
	);
}
